### ISSUE TITLE
--name=blah is also valid docker syntax

### ISSUE THREAD

**Issue by rgbkrk** [smashwilson/cringe#6]
An issue to make you cringe

lawgs

```
$ cringe
info: Deploying cringe.sh @ 230e90dcc854a586
docker pull jupyter/configurable-http-proxy
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=devtoken \
        --name=proxy \
        jupyter/configurable-http-proxy \
        --default-target http://127.0.0.1:9999
info: Launching container "run --label com.github.smashwilson.cringe=230e90dcc854a586 --net=host -d -e CONFIGPROXY_AUTH_TOKEN=devtoken --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999".
error:  Error: Command failed: docker run --label com.github.smashwilson.cringe=230e90dcc854a586 --net=host -d -e CONFIGPROXY_AUTH_TOKEN=devtoken --name=proxy jupyter/configurable-http-proxy --default-target http://127.0.0.1:9999
Error response from daemon: Conflict: The name proxy is already assigned. You have to delete (or rename) that container to be able to assign proxy to a container again.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
make: *** [proxy] Error 1
docker pull jupyter/minimal-notebook
docker build -t jupyter/tmpnb .
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=devtoken \
        --name=tmpnb \
        -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py \
        --image=jupyter/minimal-notebook --cull_timeout=60 --cull_period=30 \
        --logging=debug --pool_size=5
info: Launching container "run --label com.github.smashwilson.cringe=230e90dcc854a586 --net=host -d -e CONFIGPROXY_AUTH_TOKEN=devtoken --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image=jupyter/minimal-notebook --cull_timeout=60 --cull_period=30 --logging=debug --pool_size=5".
error:  Error: Command failed: docker run --label com.github.smashwilson.cringe=230e90dcc854a586 --net=host -d -e CONFIGPROXY_AUTH_TOKEN=devtoken --name=tmpnb -v /var/run/docker.sock:/docker.sock jupyter/tmpnb python orchestrate.py --image=jupyter/minimal-notebook --cull_timeout=60 --cull_period=30 --logging=debug --pool_size=5
Error response from daemon: Conflict: The name tmpnb is already assigned. You have to delete (or rename) that container to be able to assign tmpnb to a container again.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
make: *** [tmpnb] Error 1
error: cringe.sh @ 230e90dcc854a586: error. Error: Shell exited with status 2.
    at ChildProcess.<anonymous> (/Users/rgbkrk/.nvm/versions/node/v5.5.0/lib/node_modules/cringe/deploy.js:26:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
```

I'm using `--name=NAME` instead of `--name NAME`

**Comment by smashwilson** [comment]
Yeah, whoops!

**Comment by rgbkrk** [comment]
I ended up swapping it out for the other syntax for now.
